# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apply_cumsum_col <- function(m) {
    .Call('_NetAct_apply_cumsum_col', PACKAGE = 'NetAct', m)
}

GSEA_permute <- function(GSDB, stats_vector, nperm) {
    .Call('_NetAct_GSEA_permute', PACKAGE = 'NetAct', GSDB, stats_vector, nperm)
}

